### ISSUE TITLE
issues with empty string values for fields 

### ISSUE THREAD

**Issue by puckpuck** [evilpilaf/HoneycombSerilogSink#39]
Empty strings in Honeycomb can have unintended consequences.  An empty string will not return true for `"field" does not exist` in a filter.  This presents a problem with tracing data and .NET core 3.0 which automatically adds some tracing context to each entry.

.NET core adds a `ParentID` property, and will set the value to a blank string.  This fields needs to be undefined and for tracing to work properly in Honecyomb.  Can we add a check to only add properties that have a non-empty value before sending to Honeycomb?

**Comment by evilpilaf** [comment]
So to check on this, would the desired behaviour be to skip properties with an empty value or to send `null`/`undefined` ?

**Comment by puckpuck** [comment]
It should be to skip properties with an empty value.

**Comment by evilpilaf** [comment]
Fixed with release [v1.2.1](https://github.com/evilpilaf/HoneycombSerilogSink/releases/tag/1.2.1)
