### ISSUE TITLE
"TeamId" Should be "Dataset" in order to be consistent with Honeycomb documentation

### ISSUE THREAD

**Issue by jrmeland** [evilpilaf/HoneycombSerilogSink#56]
I just wanted to acknowledge that the term you use `teamId` should probably be `dataset` since that is the nomenclature that honeycomb uses: https://docs.honeycomb.io/api/events/#batched-events. Since honeycomb also has a "Team" name (which has little to no technical significance) it was confusing at first and I had to dig through source in order to understand what you meant.

Thanks for your work!

Josh

**Comment by evilpilaf** [comment]
Hi @jrmeland great catch, I'll get this in the next update

**Comment by evilpilaf** [comment]
Fixed in release [v1.2.1](https://github.com/evilpilaf/HoneycombSerilogSink/releases/tag/1.2.1)
